// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the BmcResetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BmcResetRequest{}

// BmcResetRequest Request to reset a Machine BMC
type BmcResetRequest struct {
	// Reset the BMC via ipmitool instead of Redfish.
	UseIpmiTool *bool `json:"useIpmiTool,omitempty"`
}

// NewBmcResetRequest instantiates a new BmcResetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBmcResetRequest() *BmcResetRequest {
	this := BmcResetRequest{}
	var useIpmiTool bool = false
	this.UseIpmiTool = &useIpmiTool
	return &this
}

// NewBmcResetRequestWithDefaults instantiates a new BmcResetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBmcResetRequestWithDefaults() *BmcResetRequest {
	this := BmcResetRequest{}
	var useIpmiTool bool = false
	this.UseIpmiTool = &useIpmiTool
	return &this
}

// GetUseIpmiTool returns the UseIpmiTool field value if set, zero value otherwise.
func (o *BmcResetRequest) GetUseIpmiTool() bool {
	if o == nil || IsNil(o.UseIpmiTool) {
		var ret bool
		return ret
	}
	return *o.UseIpmiTool
}

// GetUseIpmiToolOk returns a tuple with the UseIpmiTool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BmcResetRequest) GetUseIpmiToolOk() (*bool, bool) {
	if o == nil || IsNil(o.UseIpmiTool) {
		return nil, false
	}
	return o.UseIpmiTool, true
}

// HasUseIpmiTool returns a boolean if a field has been set.
func (o *BmcResetRequest) HasUseIpmiTool() bool {
	if o != nil && !IsNil(o.UseIpmiTool) {
		return true
	}

	return false
}

// SetUseIpmiTool gets a reference to the given bool and assigns it to the UseIpmiTool field.
func (o *BmcResetRequest) SetUseIpmiTool(v bool) {
	o.UseIpmiTool = &v
}

func (o BmcResetRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BmcResetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UseIpmiTool) {
		toSerialize["useIpmiTool"] = o.UseIpmiTool
	}
	return toSerialize, nil
}

type NullableBmcResetRequest struct {
	value *BmcResetRequest
	isSet bool
}

func (v NullableBmcResetRequest) Get() *BmcResetRequest {
	return v.value
}

func (v *NullableBmcResetRequest) Set(val *BmcResetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBmcResetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBmcResetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBmcResetRequest(val *BmcResetRequest) *NullableBmcResetRequest {
	return &NullableBmcResetRequest{value: val, isSet: true}
}

func (v NullableBmcResetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBmcResetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
