// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MachinePowerControlResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachinePowerControlResponse{}

// MachinePowerControlResponse Response for a Machine power control request.
type MachinePowerControlResponse struct {
	// ID of the Machine.
	MachineId string `json:"machineId"`
	// Power control action accepted.
	Action string `json:"action"`
	// Optional message returned by NICo Core.
	Message NullableString `json:"message"`
}

type _MachinePowerControlResponse MachinePowerControlResponse

// NewMachinePowerControlResponse instantiates a new MachinePowerControlResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachinePowerControlResponse(machineId string, action string, message NullableString) *MachinePowerControlResponse {
	this := MachinePowerControlResponse{}
	this.MachineId = machineId
	this.Action = action
	this.Message = message
	return &this
}

// NewMachinePowerControlResponseWithDefaults instantiates a new MachinePowerControlResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachinePowerControlResponseWithDefaults() *MachinePowerControlResponse {
	this := MachinePowerControlResponse{}
	return &this
}

// GetMachineId returns the MachineId field value
func (o *MachinePowerControlResponse) GetMachineId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MachineId
}

// GetMachineIdOk returns a tuple with the MachineId field value
// and a boolean to check if the value has been set.
func (o *MachinePowerControlResponse) GetMachineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MachineId, true
}

// SetMachineId sets field value
func (o *MachinePowerControlResponse) SetMachineId(v string) {
	o.MachineId = v
}

// GetAction returns the Action field value
func (o *MachinePowerControlResponse) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *MachinePowerControlResponse) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *MachinePowerControlResponse) SetAction(v string) {
	o.Action = v
}

// GetMessage returns the Message field value
// If the value is explicit nil, the zero value for string will be returned
func (o *MachinePowerControlResponse) GetMessage() string {
	if o == nil || o.Message.Get() == nil {
		var ret string
		return ret
	}

	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachinePowerControlResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// SetMessage sets field value
func (o *MachinePowerControlResponse) SetMessage(v string) {
	o.Message.Set(&v)
}

func (o MachinePowerControlResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachinePowerControlResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["machineId"] = o.MachineId
	toSerialize["action"] = o.Action
	toSerialize["message"] = o.Message.Get()
	return toSerialize, nil
}

func (o *MachinePowerControlResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"machineId",
		"action",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMachinePowerControlResponse := _MachinePowerControlResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMachinePowerControlResponse)

	if err != nil {
		return err
	}

	*o = MachinePowerControlResponse(varMachinePowerControlResponse)

	return err
}

type NullableMachinePowerControlResponse struct {
	value *MachinePowerControlResponse
	isSet bool
}

func (v NullableMachinePowerControlResponse) Get() *MachinePowerControlResponse {
	return v.value
}

func (v *NullableMachinePowerControlResponse) Set(val *MachinePowerControlResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMachinePowerControlResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMachinePowerControlResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachinePowerControlResponse(val *MachinePowerControlResponse) *NullableMachinePowerControlResponse {
	return &NullableMachinePowerControlResponse{value: val, isSet: true}
}

func (v NullableMachinePowerControlResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachinePowerControlResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
