/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// checks if the RackTaskReport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RackTaskReport{}

// RackTaskReport Structured execution report for the task. Populated on single-task `GET` and `cancel` responses, and on list responses only when `withReport=true` is set.  The body is an opaque, versioned JSON document produced by the Site execution layer. Clients **must** branch on `version` before interpreting any other field; the rest of the schema is allowed to change between versions without a breaking change to this REST API. Fields outside this anchor are not guaranteed and may be added, removed, or restructured.  **Current shape (version = 1)** — illustrative only, not part of the typed contract:  ``` {   \"version\": 1,   \"stages\": [     {       \"name\": \"string\",       \"status\": \"Pending|Running|Succeeded|Failed|Skipped\",       \"started\": \"RFC3339 timestamp\",       \"finished\": \"RFC3339 timestamp\",       \"steps\": [         {           \"name\": \"string\",           \"status\": \"Pending|Running|Succeeded|Failed|Skipped\",           \"message\": \"string\"         }       ]     }   ] } ```  Omitted when the task has not yet produced a report (e.g. still queued) or when the caller did not opt in on list endpoints.
type RackTaskReport struct {
	// Schema version of the report body. Increment on any breaking change to the rest of the document; clients must use this to pick the correct decoder.
	Version              int32 `json:"version"`
	AdditionalProperties map[string]interface{}
}

type _RackTaskReport RackTaskReport

// NewRackTaskReport instantiates a new RackTaskReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRackTaskReport(version int32) *RackTaskReport {
	this := RackTaskReport{}
	this.Version = version
	return &this
}

// NewRackTaskReportWithDefaults instantiates a new RackTaskReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRackTaskReportWithDefaults() *RackTaskReport {
	this := RackTaskReport{}
	return &this
}

// GetVersion returns the Version field value
func (o *RackTaskReport) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *RackTaskReport) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *RackTaskReport) SetVersion(v int32) {
	o.Version = v
}

func (o RackTaskReport) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RackTaskReport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RackTaskReport) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRackTaskReport := _RackTaskReport{}

	err = json.Unmarshal(data, &varRackTaskReport)

	if err != nil {
		return err
	}

	*o = RackTaskReport(varRackTaskReport)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRackTaskReport struct {
	value *RackTaskReport
	isSet bool
}

func (v NullableRackTaskReport) Get() *RackTaskReport {
	return v.value
}

func (v *NullableRackTaskReport) Set(val *RackTaskReport) {
	v.value = val
	v.isSet = true
}

func (v NullableRackTaskReport) IsSet() bool {
	return v.isSet
}

func (v *NullableRackTaskReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRackTaskReport(val *RackTaskReport) *NullableRackTaskReport {
	return &NullableRackTaskReport{value: val, isSet: true}
}

func (v NullableRackTaskReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRackTaskReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
